kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-account-manila-provisioner-operator
subjects:
- kind: ServiceAccount
  name: manila-provisioner-operator
  namespace: openshift-manila-provisioner-operator
roleRef:
  kind: ClusterRole
  name: manila-provisioner-operator
  apiGroup: rbac.authorization.k8s.io
