kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: manila-provisioner-role
subjects:
  - kind: ServiceAccount
    name: manila-provisioner
    namespace: default
roleRef:
  kind: ClusterRole
  name: manila-provisioner-runner
  apiGroup: rbac.authorization.k8s.io
