kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leader-locking-manila-provisioner
subjects:
  - kind: ServiceAccount
    name: manila-provisioner
roleRef:
  kind: Role
  name: leader-locking-manila-provisioner
  apiGroup: rbac.authorization.k8s.io
